"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    return [
        item.strip()
        for item in os.environ.get(name, default).split(",")
        if item.strip()
    ]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,[::1]',
)
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'backend.accounts.apps.AccountsConfig',
    'backend.api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', ''),
        'USER': os.environ.get('POSTGRES_USER', ''),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', ''),
        'PORT': os.environ.get('POSTGRES_PORT', ''),
        'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
    }
}

REDIS_URL = os.environ.get(
    "REDIS_URL",
    "redis://127.0.0.1:6379/1"
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "TIMEOUT" : 60*10, # 10 minutes
        "OPTIONS" : {
            "socket_connect_timeout" : 2,
            "socket_timeout" : 2,
        },
        "KEY_PREFIX" : "LLM_movie_advisor"
    }
}
REDIS_LOCK_TIMEOUT = int(os.environ.get('REDIS_LOCK_TIMEOUT', 120))
REDIS_LOCK_BLOCKING_TIMEOUT = int(os.environ.get('REDIS_LOCK_BLOCKING_TIMEOUT', 5))
TMDB_CATALOG_LOCK_TIMEOUT = int(
    os.environ.get('TMDB_CATALOG_LOCK_TIMEOUT', 1800)
)
CATALOG_SEARCH_CACHE_TIMEOUT = int(
    os.environ.get('CATALOG_SEARCH_CACHE_TIMEOUT', 600)
)

OLLAMA_BASE_URL = os.environ.get(
    'OLLAMA_BASE_URL',
    'http://127.0.0.1:11434',
).rstrip('/')
OLLAMA_CHAT_MODEL = os.environ.get('OLLAMA_CHAT_MODEL', 'llama3.1:8b')
OLLAMA_EMBEDDING_MODEL = os.environ.get(
    'OLLAMA_EMBEDDING_MODEL',
    'nomic-embed-text:latest',
)
OLLAMA_EMBEDDING_DIMENSIONS = int(
    os.environ.get('OLLAMA_EMBEDDING_DIMENSIONS', 768)
)
OLLAMA_REQUEST_TIMEOUT_SECONDS = int(
    os.environ.get('OLLAMA_REQUEST_TIMEOUT_SECONDS', 120)
)
OLLAMA_HEALTH_TIMEOUT_SECONDS = int(
    os.environ.get('OLLAMA_HEALTH_TIMEOUT_SECONDS', 2)
)
OLLAMA_CHAT_OPTIONS = {
    key: value
    for key, value in {
        'temperature': float(os.environ.get('OLLAMA_TEMPERATURE', '0.4')),
        'top_p': (
            float(os.environ['OLLAMA_TOP_P'])
            if os.environ.get('OLLAMA_TOP_P', '').strip()
            else None
        ),
        'top_k': (
            int(os.environ['OLLAMA_TOP_K'])
            if os.environ.get('OLLAMA_TOP_K', '').strip()
            else None
        ),
        'num_predict': (
            int(os.environ['OLLAMA_NUM_PREDICT'])
            if os.environ.get('OLLAMA_NUM_PREDICT', '').strip()
            else None
        ),
        'repeat_penalty': (
            float(os.environ['OLLAMA_REPEAT_PENALTY'])
            if os.environ.get('OLLAMA_REPEAT_PENALTY', '').strip()
            else None
        ),
    }.items()
    if value is not None
}
LLM_CATALOG_CONTEXT_CACHE_TIMEOUT = int(
    os.environ.get('LLM_CATALOG_CONTEXT_CACHE_TIMEOUT', 300)
)
LLM_CATALOG_CANDIDATE_LIMIT = int(
    os.environ.get('LLM_CATALOG_CANDIDATE_LIMIT', 12)
)
LLM_CATALOG_OVERVIEW_MAX_LENGTH = int(
    os.environ.get('LLM_CATALOG_OVERVIEW_MAX_LENGTH', 600)
)
LLM_CATALOG_SEARCH_TERM_LIMIT = int(
    os.environ.get('LLM_CATALOG_SEARCH_TERM_LIMIT', 10)
)
LLM_USER_PREFERENCE_LIMIT = int(
    os.environ.get('LLM_USER_PREFERENCE_LIMIT', 20)
)
LLM_USER_INTERACTION_LIMIT = int(
    os.environ.get('LLM_USER_INTERACTION_LIMIT', 20)
)
LLM_PROFILE_SUMMARY_MAX_LENGTH = int(
    os.environ.get('LLM_PROFILE_SUMMARY_MAX_LENGTH', 1500)
)
LLM_PREFERENCE_VALUE_MAX_LENGTH = int(
    os.environ.get('LLM_PREFERENCE_VALUE_MAX_LENGTH', 300)
)
LLM_EMBEDDING_MODEL_VERSION = os.environ.get(
    'LLM_EMBEDDING_MODEL_VERSION',
    'v1',
)
LLM_EMBEDDING_SOURCE_LANGUAGE = os.environ.get(
    'LLM_EMBEDDING_SOURCE_LANGUAGE',
    'pl-PL',
)
LLM_EMBEDDING_BATCH_SIZE = int(
    os.environ.get('LLM_EMBEDDING_BATCH_SIZE', 32)
)
LLM_EMBEDDING_SYNC_LOCK_TIMEOUT = int(
    os.environ.get('LLM_EMBEDDING_SYNC_LOCK_TIMEOUT', 3600)
)
LLM_SEMANTIC_SEARCH_ENABLED = env_bool('LLM_SEMANTIC_SEARCH_ENABLED', True)
LLM_SEMANTIC_MIN_SIMILARITY = float(
    os.environ.get('LLM_SEMANTIC_MIN_SIMILARITY', 0.2)
)
if OLLAMA_EMBEDDING_DIMENSIONS != 768:
    raise ImproperlyConfigured(
        'OLLAMA_EMBEDDING_DIMENSIONS must be 768 for the current pgvector schema.'
    )
if LLM_EMBEDDING_BATCH_SIZE < 1:
    raise ImproperlyConfigured('LLM_EMBEDDING_BATCH_SIZE must be positive.')
if not 0 <= LLM_SEMANTIC_MIN_SIMILARITY <= 1:
    raise ImproperlyConfigured(
        'LLM_SEMANTIC_MIN_SIMILARITY must be between 0 and 1.'
    )

SESSION_ENGINE = "backend.sessions"
SESSION_CACHE_ALIAS = "default"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    ('frontend', BASE_DIR / 'frontend' / 'dist'),
]

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Production security. Local defaults remain HTTP-friendly while setting
# DJANGO_DEBUG=False enables secure cookies, HTTPS redirect and HSTS.

SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SECURE_COOKIES', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_SECURE_COOKIES', not DEBUG)
SECURE_HSTS_SECONDS = int(
    os.environ.get('DJANGO_HSTS_SECONDS', '0' if DEBUG else '31536000')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_HSTS_INCLUDE_SUBDOMAINS',
    not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_HSTS_PRELOAD', False)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

if env_bool('DJANGO_TRUST_X_FORWARDED_PROTO', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get('DJANGO_MAX_REQUEST_BYTES', str(2 * 1024 * 1024))
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': os.environ.get(
                'DJANGO_REQUEST_LOG_LEVEL',
                'ERROR' if DEBUG else 'WARNING',
            ),
            'propagate': False,
        },
        'django.security.csrf': {
            'handlers': ['console'],
            'level': os.environ.get(
                'DJANGO_REQUEST_LOG_LEVEL',
                'ERROR' if DEBUG else 'WARNING',
            ),
            'propagate': False,
        },
    },
}
